version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whatsapp
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  backend:
    build:
      context: ./whatapps
      dockerfile: dockerfile-spring
    container_name: spring-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/whatsapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    volumes:
      - ./whatapps:/app  # Mount local code into the container
    depends_on:
      mysql:
        condition: service_healthy



  frontend:
    build:
      context: ./whatsapp_frontend
      dockerfile: dockerfile-next
    container_name: next-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./whatsapp_frontend:/app  # Mount local code into the container
      - /app/node_modules  # Prevents overwriting `node_modules`
    depends_on:
      - backend
